### ISSUE TITLE
Upload CSV issue "fqdn: Not a valid FQDN"

### ISSUE THREAD

**Issue by JoeApo108** [pokt-foundation/node-nanny#138]
**Describe the bug**
While uploading batch configuration via upload CSV I've found FQDN in CSV has to be valid with domain suffix. Since this is not mandatory when creating a host manually I call for disabling the check for FQDN as when in use with docker I use only the container name for the connection.

**To Reproduce**
1. Edit .CSV file with FQDN following: **pokt-000**
2.  Go to 'Host'
3. Upload .CSV
5. Warning: There were one or more issues with your CSV format. Please correct the following issues before attempting to create hosts via CSV.
[Pokt-000]: fqdn: Not a valid FQDN

**Expected behavior**
I expect not to validate FQDN as some use cases (docker CTs link) don't provide it

**Docker image**
 - node-nanny:latest-beta
 - node-nanny-ui:latest-beta

**Comment by commoddity** [comment]
@JoeApo108 This was brought up by a tester a while back and I did disable the FQDN regex to allow for entering in a Docker container name, for example. So currently if you do need to add a host with a container name in the FQDN field you may do so using the form input.

However, I did not update the CSV upload, so I will push an updated release shortly, that allows entering container names into the FQDN field for CSV upload to fit your use case. Will update when it's ready to go.

**Comment by JoeApo108** [comment]
@commoddity I hereby confirm that FQDN is not checked for batch host upload via CSV in the latest update.

**Comment by commoddity** [comment]
Fantastic. Closed.
